name: Deploy Portfolio

on:
  push:
    branches:
      - main  # Change if your branch is different

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Create .env file
        run: |
          echo "VITE_EMAILJS_SERVICE_ID=${{ secrets.VITE_EMAILJS_SERVICE_ID }}" >> .env
          echo "VITE_EMAILJS_TEMPLATE_ID=${{ secrets.VITE_EMAILJS_TEMPLATE_ID }}" >> .env
          echo "VITE_SANITY_PROJECT_ID=${{ secrets.VITE_SANITY_PROJECT_ID }}" >> .env
          echo "VITE_SANITY_TOKEN=${{ secrets.VITE_SANITY_TOKEN }}" >> .env

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Deploy to GitHub Pages
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

          git clone git@github.com:mda1458/mda1458.github.io.git deploy
          rm -rf deploy/*
          cp -r dist/* deploy/
          cd deploy
          git add .
          git commit -m "Deploy: $(date)"
          git push origin main
